//
// Created by Keaton Burleson on 11/29/21.
//

#ifndef HONORSPROJECT_CONSUMABLETYPE_H
#define HONORSPROJECT_CONSUMABLETYPE_H
enum ConsumableType {
    COFFEE_FILTER, COFFEE_GROUNDS, FLAVOR_ADDITIVE
};
#endif //HONORSPROJECT_CONSUMABLETYPE_H
