//
// Created by Keaton Burleson on 11/28/21.
//

#ifndef HONORSPROJECT_BREWSTATUS_H
#define HONORSPROJECT_BREWSTATUS_H
enum BrewStatus {
    PAUSED, BREWING, FINISHED, WAITING
};
#endif //HONORSPROJECT_BREWSTATUS_H
